### ISSUE TITLE
Working with drone 0.7 ?

### ISSUE THREAD

**Issue by b-connect** [drone/drone-node#7]
Is this lib working with latest drone version?

**Comment by b-connect** [comment]
Seem not to ;- )

**Comment by xap5xap** [comment]
Hello guys. Can anybody confirm if this version of drone-node (1.0.1) works with drone 0.7?

**Comment by janeklb** [comment]
I'm having issues with drone 0.8:

```javascript
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.process.stdin.on (/xxx/node_modules/drone-node/lib/plugin.js:26:37)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by tboerger** [comment]
This lib had been targeting drone 0.4, since drone 0.5 you don't need to parse any json payload anymore, you just need to accept specific environment variables.

**Comment by tboerger** [comment]
The new upcoming version will only target Drone >=1.1.6
